run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  exclude-dirs:
    - "^sysinfo$"
    - "^xbps-src$"
    - "^plugin$"
    - "^usergroups$"
    - "^vmman$"
    - "^xbps-pkg$"
    - "^pluginentry$"
