version: 2

run:
  timeout: 1m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - unused
    - revive
    - misspell

linters-settings:
  govet:
    enabled: false
  ineffassign:
    enabled: false

issues:
  exclude-dirs:
    - "^infman$"
    - "^srcman$"
    - "^serman$"
    - "^ugsman$"
    - "^vmsman$"
    - "^pkgman$"
  exclude-rules:
    - linters:
        - revive
      text: "type name will be used as srcman.SrcmanConfig"
